version: 0.2
phases:
  install:
    commands:
      - yum -y update
      - yum -y install docker
  build:
    commands:
      - |
        if [ $ROLLBACK = true ]
        then 
          echo START ROLLBACK 
        else
          echo NO ROLLBACL
      - echo $FIX_HASH
